version: '3'
services:
  discoveryapi:
    restart: always
    build:
      context: .
      dockerfile: discovery.Dockerfile
    ports:
      - "8003:80"  # Expose Discovery Plugin API on port 8000
    depends_on:
      - ckan  # Ensure ckan is ready before starting API
    volumes:
      - .:/app 
  publishapi:
    restart: always
    build:
      context: .
      dockerfile: publish.Dockerfile
    ports:
      - "8004:80"  # Expose Publish Plugin API on port 8000
    depends_on:
      - ckan  # Ensure ckan is ready before starting API
    volumes:
      - .:/app 

  datapusher:
    restart: always
    container_name: datapusher
    build:
      context: ./custom-docker/
      dockerfile: datapusher.Dockerfile
    ports:
      - "8800:8800"

  db:
    container_name: db
    restart: always
    build:
      context: ./docker-ckan/postgresql/
      args:
        - DATASTORE_READONLY_PASSWORD=${DATASTORE_READONLY_PASSWORD}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    environment:
      - DATASTORE_READONLY_PASSWORD=${DATASTORE_READONLY_PASSWORD}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=/var/lib/postgresql/data/db
    volumes:
      - pg_data:/var/lib/postgresql/data

  solr:
    container_name: solr
    restart: always
    image: ckan/ckan-solr:2.9-solr8
    volumes:
      - solr_data:/var/solr

  redis:
    container_name: redis
    image: redis:alpine
    restart: always

  ckan:
    container_name: ckan
    restart: always
    build:
      context: ./docker-ckan/ckan/
      dockerfile: Dockerfile
      args:
        - TZ=${TZ}
    env_file:
      - .env
    links:
      - db
      - solr
      - redis
      - datapusher
    ports:
      - "0.0.0.0:${CKAN_PORT}:5000"
    volumes:
      - ckan_storage:/var/lib/ckan

volumes:
  ckan_storage:
  pg_data:
  solr_data:
